In [63]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [52]:
df = pd.read_csv(r"..\data\raw\Nifty_50_1y_dataset.csv", header=[0,1], index_col=0)
df.head(10)

Ticker     ASIANPAINT.NS                                                  \
Price               Open         High          Low        Close   Volume
Date
2025-06-05   2227.045252  2236.839365  2209.138568  2219.526367   996614
2025-06-06   2225.066478  2228.529077  2215.074309  2221.208008   822087
2025-06-09   2216.063665  2231.694877  2212.106409  2223.879150  1041851
2025-06-10   2236.509602  2236.509602  2211.748197  2215.442383  1809051
2025-06-11   2205.557794  2222.431362  2203.760550  2205.358154  1430888
2025-06-12   2220.534580  2259.473811  2204.659453  2215.941650  3417373
2025-06-13   2171.610887  2213.645383  2171.411247  2210.749756  1786807
2025-06-16   2210.749588  2246.493850  2205.857321  2241.302002  1301826
2025-06-17   2227.523615  2277.445704  2223.529848  2261.270996  1540986
2025-06-18   2253.483089  2280.441017  2251.486205  2277.844971  1131156

Ticker     BHARTIARTL.NS                                                  ...  \
Price               Open         High          Low        Close   Volume  ...
Date                                                                      ...
2025-06-05   1868.380473  1873.339020  1853.108124  1863.223633  8999675  ...
2025-06-06   1856.579218  1866.298019  1851.819086  1854.694946  4644174  ...
2025-06-09   1858.463445  1859.455154  1833.373148  1849.637207  3649505  ...
2025-06-10   1851.124730  1860.050115  1834.959940  1841.703491  7925901  ...
2025-06-11   1842.496973  1851.025650  1832.480732  1844.777832  8907265  ...
2025-06-12   1856.380823  1867.388773  1816.414886  1828.910400  7346031  ...
2025-06-13   1799.952525  1829.307099  1799.952525  1825.141968  4613000  ...
2025-06-16   1826.827881  1854.496598  1823.555313  1845.868774  5722187  ...
2025-06-17   1863.421926  1863.421926  1832.282227  1839.422607  6561555  ...
2025-06-18   1832.282333  1855.488358  1827.819640  1850.430664  5069427  ...

Ticker         SBIN.NS                                                \
Price             Open        High         Low       Close    Volume
Date
2025-06-05  794.381210  797.328092  788.634754  791.729004  13595507
2025-06-06  792.367529  801.993999  788.880337  798.654175  17163935
2025-06-09  802.927230  809.901494  801.257318  805.530273  12793040
2025-06-10  806.463448  807.494844  800.176742  802.583374   6560513
2025-06-11  802.534260  806.070495  798.654186  800.618774   7197825
2025-06-12  801.551975  802.043122  787.014035  791.679932  13448521
2025-06-13  772.328709  782.200752  772.328709  778.320679  11377117
2025-06-16  778.468079  781.316756  772.230535  778.468079   8085001
2025-06-17  779.941518  784.705621  776.552592  778.271606   7753156
2025-06-18  778.468076  781.414958  774.391531  777.878723   5710169

Ticker       SBILIFE.NS
Price              Open         High          Low        Close   Volume
Date
2025-06-05  1779.526260  1788.513766  1762.549859  1772.336304   912222
2025-06-06  1772.336298  1781.024172  1748.868921  1778.128174  1589674
2025-06-09  1787.115680  1796.502655  1756.658019  1788.314087  1221496
2025-06-10  1788.413890  1794.105929  1769.540103  1783.021362  1400311
2025-06-11  1783.021355  1798.400001  1771.537319  1796.802246  1089930
2025-06-12  1797.401427  1809.784238  1757.556791  1763.548462   984693
2025-06-13  1717.612340  1764.047790  1717.612340  1752.763428  1774169
2025-06-16  1759.553971  1797.501218  1749.468016  1795.304321   728053
2025-06-17  1793.606644  1804.191904  1782.921546  1797.700928   557790
2025-06-18  1797.501240  1802.494299  1788.813366  1794.705078   349531

[10 rows x 252 columns]

In [53]:
close_prices = df.xs(key='Close', axis=1, level=1).copy()
close_prices

Ticker,ASIANPAINT.NS,BHARTIARTL.NS,INDUSINDBK.NS,COALINDIA.NS,CIPLA.NS,APOLLOHOSP.NS,BAJFINANCE.NS,ITC.NS,POWERGRID.NS,BAJAJ-AUTO.NS,...,TATASTEEL.NS,LT.NS,HEROMOTOCO.NS,RELIANCE.NS,ICICIBANK.NS,HINDALCO.NS,ULTRACEMCO.NS,NTPC.NS,SBIN.NS,SBILIFE.NS
Date,,,,,,,,,,,,,,,,,,,,,
2025-06-05,2219.526367,1863.223633,803.200012,368.960266,1460.353394,6858.104980,893.400024,399.610260,284.937286,8230.154297,...,154.370010,3607.365723,4037.947266,1430.050171,1443.660645,632.610779,11088.711914,320.199554,791.729004,1772.336304
2025-06-06,2221.208008,1854.694946,822.849976,372.744232,1474.468628,6924.432129,937.150024,401.469574,286.438232,8306.613281,...,157.490005,3620.933105,4124.041992,1431.140747,1448.523071,645.416870,11182.120117,324.291595,798.654175,1778.128174
2025-06-09,2223.879150,1849.637207,836.650024,374.659576,1476.821167,6913.959473,960.750000,403.376556,290.989502,8310.459961,...,157.320007,3643.314453,4202.696289,1436.395386,1423.813843,646.062073,11189.076172,328.432312,805.530273,1788.314087
2025-06-10,2215.442383,1841.703491,845.049988,373.304810,1480.938232,6900.494629,949.750000,407.142883,291.522064,8296.034180,...,155.679993,3644.205811,4231.297852,1426.183472,1412.004883,653.557129,11319.250977,330.478333,802.583374,1783.021362
2025-06-11,2205.358154,1844.777832,836.299988,375.687378,1491.622803,6909.471680,942.500000,406.332397,286.099335,8385.476562,...,156.410004,3649.157471,4261.542480,1436.494507,1420.042847,650.430054,11391.791016,329.406616,800.618774,1796.802246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-01,2632.399902,1810.599976,901.150024,472.600006,1377.378174,8108.500000,889.049988,279.649994,286.149994,10376.000000,...,210.570007,4010.800049,4819.899902,1313.924927,1239.699951,1141.300049,11232.000000,378.700012,954.099976,1812.500000
2026-06-02,2660.699951,1814.199951,912.500000,472.149994,1366.480347,8089.500000,882.000000,283.250000,282.149994,10281.000000,...,210.600006,4000.899902,4875.000000,1308.549805,1226.599976,1146.300049,11165.000000,367.399994,956.650024,1801.699951
2026-06-03,2662.399902,1824.099976,899.950012,472.299988,1362.418335,8290.500000,876.799988,277.000000,285.049988,10259.000000,...,211.889999,3953.199951,4840.899902,1307.156250,1242.000000,1138.900024,11101.000000,366.799988,970.450012,1784.199951
2026-06-04,2661.600098,1818.900024,903.200012,481.649994,1385.699951,8249.000000,874.400024,280.299988,284.600006,10362.000000,...,210.570007,3942.100098,4882.299805,1297.699951,1251.699951,1125.599976,10997.000000,366.399994,979.250000,1764.900024
2026-06-05,2686.699951,1798.199951,904.799988,472.299988,1401.300049,8304.500000,889.400024,280.700012,285.649994,10342.000000,...,206.770004,3953.199951,4835.000000,1291.000000,1262.099976,1092.599976,10912.000000,361.649994,977.700012,1782.800049

In [54]:
close_prices.isnull().sum()

Ticker
ASIANPAINT.NS      0
BHARTIARTL.NS      0
INDUSINDBK.NS      0
COALINDIA.NS       0
CIPLA.NS           0
APOLLOHOSP.NS      0
BAJFINANCE.NS      0
ITC.NS             0
POWERGRID.NS       0
BAJAJ-AUTO.NS      0
DIVISLAB.NS        1
INFY.NS            0
ADANIPORTS.NS      0
TCS.NS             0
MARUTI.NS          0
TATAMOTORS.NS    250
HDFCLIFE.NS        0
M&M.NS             0
GRASIM.NS          0
DRREDDY.NS         0
ONGC.NS            0
TECHM.NS           0
EICHERMOT.NS       0
TATACONSUM.NS      0
HDFCBANK.NS        0
SHRIRAMFIN.NS      0
KOTAKBANK.NS       0
SUNPHARMA.NS       0
HINDUNILVR.NS      0
JSWSTEEL.NS        0
NESTLEIND.NS       0
LTIM.NS          250
BPCL.NS            0
BAJAJFINSV.NS      0
TITAN.NS           0
AXISBANK.NS        0
BRITANNIA.NS       0
ADANIENT.NS        0
WIPRO.NS           0
HCLTECH.NS         0
TATASTEEL.NS       0
LT.NS              0
HEROMOTOCO.NS      0
RELIANCE.NS        0
ICICIBANK.NS       0
HINDALCO.NS        0
ULTRACEMCO.NS      0
NTPC.NS            0
SBIN.NS            0
SBILIFE.NS         0
dtype: int64

In [55]:
close_prices.drop(columns=['LTIM.NS', 'TATAMOTORS.NS'], inplace=True)

In [56]:
close_prices.isnull().sum()

Ticker
ASIANPAINT.NS    0
BHARTIARTL.NS    0
INDUSINDBK.NS    0
COALINDIA.NS     0
CIPLA.NS         0
APOLLOHOSP.NS    0
BAJFINANCE.NS    0
ITC.NS           0
POWERGRID.NS     0
BAJAJ-AUTO.NS    0
DIVISLAB.NS      1
INFY.NS          0
ADANIPORTS.NS    0
TCS.NS           0
MARUTI.NS        0
HDFCLIFE.NS      0
M&M.NS           0
GRASIM.NS        0
DRREDDY.NS       0
ONGC.NS          0
TECHM.NS         0
EICHERMOT.NS     0
TATACONSUM.NS    0
HDFCBANK.NS      0
SHRIRAMFIN.NS    0
KOTAKBANK.NS     0
SUNPHARMA.NS     0
HINDUNILVR.NS    0
JSWSTEEL.NS      0
NESTLEIND.NS     0
BPCL.NS          0
BAJAJFINSV.NS    0
TITAN.NS         0
AXISBANK.NS      0
BRITANNIA.NS     0
ADANIENT.NS      0
WIPRO.NS         0
HCLTECH.NS       0
TATASTEEL.NS     0
LT.NS            0
HEROMOTOCO.NS    0
RELIANCE.NS      0
ICICIBANK.NS     0
HINDALCO.NS      0
ULTRACEMCO.NS    0
NTPC.NS          0
SBIN.NS          0
SBILIFE.NS       0
dtype: int64

In [57]:
close_prices = close_prices.ffill().dropna(axis=0)

In [58]:
daily_returns = close_prices.pct_change().dropna()

In [59]:
annual_returns = daily_returns.mean() * 252

In [61]:
annual_volatility = daily_returns.std() * np.sqrt(252)

In [62]:
clustering_data = pd.DataFrame({
    'Return': annual_returns,
    'Volatility': annual_volatility
})

In [64]:
scaler = StandardScaler()
scaled_features = scaler.fit_transform(clustering_data)

In [65]:
k_means_ready = pd.DataFrame(
    scaled_features,
    index=clustering_data.index,
    columns=clustering_data.columns
)

In [67]:
k_means_ready.head()

                 Return  Volatility
Ticker
ASIANPAINT.NS  0.749721    0.070582
BHARTIARTL.NS -0.443220   -1.071052
INDUSINDBK.NS  0.441539    1.250499
COALINDIA.NS   1.012636   -0.411646
CIPLA.NS      -0.457034   -0.633873