In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"..\data\raw\Nifty_50_1y_dataset.csv")
df.head(10)

,Ticker,ASIANPAINT.NS,ASIANPAINT.NS.1,ASIANPAINT.NS.2,ASIANPAINT.NS.3,ASIANPAINT.NS.4,BHARTIARTL.NS,BHARTIARTL.NS.1,BHARTIARTL.NS.2,BHARTIARTL.NS.3,...,SBIN.NS,SBIN.NS.1,SBIN.NS.2,SBIN.NS.3,SBIN.NS.4,SBILIFE.NS,SBILIFE.NS.1,SBILIFE.NS.2,SBILIFE.NS.3,SBILIFE.NS.4
0,Price,Open,High,Low,Close,Volume,Open,High,Low,Close,...,Open,High,Low,Close,Volume,Open,High,Low,Close,Volume
1,Date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-06-05,2227.0452515829743,2236.8393653714897,2209.138568277106,2219.5263671875,996614,1868.3804731686369,1873.3390200719505,1853.1081244947754,1863.2236328125,...,794.3812098308251,797.3280919793597,788.6347536685006,791.72900390625,13595507,1779.5262600416722,1788.5137664055192,1762.5498591321839,1772.3363037109375,912222
3,2025-06-06,2225.066477788955,2228.5290771994382,2215.0743085917125,2221.2080078125,822087,1856.5792184367435,1866.2980193721837,1851.8190857596499,1854.6949462890625,...,792.3675287830383,801.9939985959651,788.88033690073,798.6541748046875,17163935,1772.3362984402731,1781.0241724724792,1748.8689207822392,1778.128173828125,1589674
4,2025-06-09,2216.0636653265124,2231.6948769865094,2212.1064087812865,2223.879150390625,1041851,1858.463445042735,1859.4551544584463,1833.373148401931,1849.63720703125,...,802.9272300169949,809.9014942207324,801.2573180380161,805.5302734375,12793040,1787.115679595648,1796.502655036041,1756.6580192406734,1788.3140869140625,1221496
5,2025-06-10,2236.5096020141245,2236.5096020141245,2211.7481969540704,2215.4423828125,1809051,1851.1247304530432,1860.050114998196,1834.959939967343,1841.7034912109375,...,806.4634476687678,807.4948444720902,800.1767415127031,802.5833740234375,6560513,1788.4138903849116,1794.1059288635151,1769.540103054554,1783.0213623046875,1400311
6,2025-06-11,2205.5577938919528,2222.4313617191465,2203.7605500158743,2205.358154296875,1430888,1842.4969729787406,1851.0256498593915,1832.4807319540828,1844.77783203125,...,802.5342598525855,806.0704945433416,798.6541862626485,800.6187744140625,7197825,1783.0213546039022,1798.4000005807684,1771.53731899598,1796.80224609375,1089930
7,2025-06-12,2220.53458020989,2259.4738107081753,2204.6594529723643,2215.941650390625,3417373,1856.3808230050638,1867.3887729729095,1816.4148863444686,1828.910400390625,...,801.5519752269744,802.0431222706184,787.0140347260071,791.679931640625,13448521,1797.4014267579296,1809.7842376203967,1757.5567910355323,1763.5484619140625,984693
8,2025-06-13,2171.6108865639185,2213.6453832975812,2171.411246958574,2210.749755859375,1786807,1799.952525301367,1829.3070987475194,1799.952525301367,1825.1419677734375,...,772.3287088939938,782.2007522600275,772.3287088939938,778.3206787109375,11377117,1717.6123402295552,1764.047790125296,1717.6123402295552,1752.763427734375,1774169
9,2025-06-16,2210.749588087704,2246.493850099095,2205.857321207117,2241.302001953125,1301826,1826.827881095153,1854.4965978631628,1823.5553126750672,1845.8687744140625,...,778.4680786132812,781.3167555010375,772.2305350251097,778.4680786132812,8085001,1759.5539705170804,1797.5012184623977,1749.4680158381009,1795.3043212890625,728053

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Columns: 253 entries, Ticker to SBILIFE.NS.4
dtypes: object(253)
memory usage: 498.2+ KB

In [6]:
df.describe()

,Ticker,ASIANPAINT.NS,ASIANPAINT.NS.1,ASIANPAINT.NS.2,ASIANPAINT.NS.3,ASIANPAINT.NS.4,BHARTIARTL.NS,BHARTIARTL.NS.1,BHARTIARTL.NS.2,BHARTIARTL.NS.3,...,SBIN.NS,SBIN.NS.1,SBIN.NS.2,SBIN.NS.3,SBIN.NS.4,SBILIFE.NS,SBILIFE.NS.1,SBILIFE.NS.2,SBILIFE.NS.3,SBILIFE.NS.4
count,252,251,251,251,251,251,251,251,251,251,...,251,251,251,251,251,251,251,251,251,251
unique,252,245,246,249,246,249,226,245,243,241,...,249,250,251,242,249,248,249,247,240,249
top,Price,2880.0,2916.0,2500.0,2371.698486328125,0,1930.0,1919.9000244140625,1883.0,2066.300048828125,...,969.9000244140625,972.5,Low,801.9940185546875,0,1839.0,1819.0,1825.0,1807.2877197265625,0
freq,1,3,2,2,2,3,4,2,3,2,...,2,2,1,2,3,2,2,2,3,3